@startuml
skinparam actorStyle awesome
left to right direction

actor Usuario as user

' Package de zoológico.
package Zoo {
  usecase (Colocar\nhabitat) as ColHabitat
  usecase (Colocar\nanimal) as ColAnimal
  usecase (Colocar\ncomida) as ColComida
  usecase (Explorar\nzoo) as ExZoo

  usecase (Elegir\ntipo de\nhabitat) as TipoHabitat
  usecase (Mostrar\nconflictos\nhabitat) as ConfHabitat

  usecase (Elegir\ntipo de\nanimal) as TipoAnimal
  usecase (Mostrar\nconflictos\nanimal) as ConfAnimal
  
  usecase (Elegir\ntipo de \ncomida) as TipoComida

  usecase (Ver\nhabitats) as VerHabitats
  usecase (Ver\nanimales) as VerAnimales
  usecase (Ver\ndepositos de\ncomida) as VerDepsComida
}


' Includes, un caso de uso incluye, implica, este otro caso de uso.
ColHabitat ..> TipoHabitat : <<Include>>
ColAnimal ..> TipoAnimal : <<Include>>
ColComida ..> TipoComida : <<Include>>
ExZoo ..> VerHabitats : <<Include>>
VerHabitats ..> VerAnimales : <<Include>>
VerHabitats ..> VerDepsComida : <<Include>>

' Extends, estas son situaciones opcionales que se ramifican de un caso de uso.
ColHabitat <.. ConfHabitat : <<Extend>>
ColAnimal <.. ConfAnimal : <<Extend>>


' Casos de uso usuario principal.
user --> ColHabitat
user --> ColAnimal
user --> ColComida
user --> ExZoo


@enduml